require('plugins')
require('keymaps')
require('settings')
require('lsp')
require('treesitter-config')
require('telescope-config')
require('statline.init')
require('theme')
require('nvim-tree-config')
require('whichkey-conf')
require('dashboard-config')
require('appearance')
require('flutter')
require('toggleterm-config')
require('autopairs-config')

