return {
	-- {
	-- 	'nvim-orgmode/orgmode',
	-- 	event = 'VeryLazy',
	-- 	ft = { 'org' },
	-- 	dependencies = {
	-- 		{ 'akinsho/org-bullets.nvim' },
	-- 	},
	-- 	config = function()
	-- 		-- Setup orgmode
	-- 		require('orgmode').setup({
	-- 			-- org_agenda_files = '~/orgfiles/**/*',
	-- 			-- org_default_notes_file = '~/orgfiles/refile.org',
	-- 			org_agenda_files = '~/org/**/*',
	-- 			org_default_notes_file = '~/org/refile.org',
	--
	-- 		})
	-- 		require('org-bullets').setup()
	-- 	end,
	-- },
	--
	-- {
	-- 	"chipsenkbeil/org-roam.nvim",
	-- 	dependencies = {
	-- 		{ "nvim-orgmode/orgmode" },
	-- 	},
	-- 	config = function()
	-- 		require("org-roam").setup({
	-- 			directory = "~/org",
	-- 			-- bindings = {
	-- 			-- 	prefix = "<Leader>o",
	-- 			-- },
	-- 		})
	-- 	end
	-- }
}
